### ISSUE TITLE
Feature request:  Timeline mode start/end frame keyboard shortcut

### ISSUE THREAD

**Issue by dheista** [Grix/ildagen#12]
On a Mac, for example:

In the Editor mode, It would be nice to have a keyboard shortcut for Setting the start frame or end frame (Maybe CTRL-1 and CTRL-0)

**Comment by Grix** [comment]
Ctrl+N and ? are mentioned in other issue trackers so I edited this one to only cover start/end frames.

**Comment by Grix** [comment]
Fixed in v1.9.6. You can use CTRL/CMD+1 and +2.

**Comment by dheista** [comment]
Hmm - I just tried in 1.9.6 using CMD+1 and CMD+2 to set the start and end frames for scope, but no dialog came up.
I also tried CTRL+1 and CTRL+2 on the same macbook pro, to no avail.
Does it work on a PC?  Or an older mac/os?

**Comment by Grix** [comment]
Oh I may have misunderstood you. The shortcuts does not bring up a dialog, but instead they set the borders where the mouse currently is. So you can position your mouse where you want it and then press the keyboard shortcuts.

**Comment by dheista** [comment]
Well I just tried that as well, using the mouse cursor from the trackpad hovering over the timeline in the frame editor, and hit CMD+1 or CTRL+1 and nothing happened.  Tried a few different ways.  Is it confirmed in a different mac os?

**Comment by Grix** [comment]
I think I see, you are talking about the scope in the editor mode? What I added was the end/start of file in the timeline mode. I was confused because I see now that the title of this issue mentions the timeline mode but the text mentions the editor mode.

**Comment by dheista** [comment]
Ah shit - you're right.  I did mean the editor mode, just because I spend a fair amount of time dinking around with changing scope in the editor while making more complex patterns.  Sorry!

**Comment by Grix** [comment]
Shortcuts for setting the scope was added in the most recent version (keys 1 and 2 when mouse is over the mini-timeline in editor mode).
