### ISSUE TITLE
Bug: Frame number in timeline too small

### ISSUE THREAD

**Issue by dheista** [Grix/ildagen#14]
You can see the incredibly small frame numbers in the timeline window, on a Macbook pro M1 with retina display.  For scale, compare to the other text on the page.  I have the application in full screen mode in the first image, and the second image is the same application session, in editor mode where you can see the frame number text is much bigger than in the timeline window.

<img width="1598" alt="Screen Shot 2021-12-27 at 4 34 28 PM" src="https://user-images.githubusercontent.com/1724371/147508734-482a2c0a-252c-4894-b8b0-1e1cf690cc8b.png">

<img width="1283" alt="Screen Shot 2021-12-27 at 4 41 39 PM" src="https://user-images.githubusercontent.com/1724371/147509015-8bbe3788-3ae1-4b42-b449-1ebbeee2c5e8.png">

**Comment by Grix** [comment]
Fixed in 1.9.6
