### ISSUE TITLE
macOS Version displays error on start

### ISSUE THREAD

**Issue by f-fritz** [Grix/ildagen#2]
Trying to launch the 1.8.1 macOS version of LaserShowGen, I just get a little window saying "Unable to find game!!:". Hitting "Ok" closes the app.

Tried this on two Macs both running macOS Catalina.
<img width="553" alt="LaserShowGen macOS error" src="https://user-images.githubusercontent.com/46245228/68246714-ac1d3880-0019-11ea-8f76-3fe456f0a42e.png">

**Comment by Grix** [comment]
Hi, make sure the program is placed in the Application folder, that usually solves this issue. I think it has something to do with the way the file is zipped making mac mark the files as quarantined. If placing it in the Applications folder doesn't work, you can also try to run the following command to release the quarantine: sudo xattr -d com.apple.quarantine LaserShowGen.app
