### ISSUE TITLE
UI won't scale well on HighRes screen

### ISSUE THREAD

**Issue by f-fritz** [Grix/ildagen#3]
While the canvas does, the rest of the UI elements won't scale on a HighRes screen like of a MacBook Pro (running Parallels Desktop virtualization).

The two attached screenshots may look okay on a desktop but it's hard to work with on a 15" laptop screen. (2880x1800)
<img width="1920" alt="Bildschirmfoto 2019-11-05 um 22 31 41" src="https://user-images.githubusercontent.com/46245228/68248036-572ef180-001c-11ea-96c1-17948a33783b.png">
<img width="1920" alt="Bildschirmfoto 2019-11-05 um 22 31 46" src="https://user-images.githubusercontent.com/46245228/68248038-572ef180-001c-11ea-99f9-89632e0e715f.png">

**Comment by Grix** [comment]
Fixed with a basic dynamic scaling system in v1.8.4
