### ISSUE TITLE
Feature Request: When in editor mode, typing ? button would show the help screen

### ISSUE THREAD

**Issue by dheista** [Grix/ildagen#5]
Instead of only using the mouse to hover over the help? icon in the editor mode, if I type the ? key - the help display would show up

**Comment by Grix** [comment]
I can add a keyboard shortcut but it would have to be something other than ? since that key varies a lot in different keyboard layouts. In mine, for example, it's not a single key but SHIFT+another key to type ?, that's not practical as a shortcut. Any suggestions?

**Comment by dheista** [comment]
That's an interesting problem I hadn't thought of.  The ? key on US keyboards also require two clicks, but I would think it's a pretty normal action/behavior for a user to be asked to perform...  I wouldn't shy away from a two-click (SHIFT+?) hotkey, because really vigorous keyboard users like myself would probably be quite happy making 2 key presses to avoid going back and forth from the mouse/trackpad...

**Comment by Grix** [comment]
You can now use Ctrl/Cmd+F1 to do this in v1.9.6. The question mark shortcut is too inpractical to use instead, not only because of what we discussed above but also because there isn't a dedicated designator for a question mark key in the development engine I use, so we'd have to design a dedicated system just to detect when that key is down. So I'm closing this for now.

**Comment by dheista** [comment]
Hmm - dang, ok, on my MBP - to get the functionality to work I have to press CMD + FN + F1, and it's only a momentary display instead of toggle.  If it works on a PC keyboard with just CTRL-F1 or on an older mac with CMD-F1, that's better than no keyboard command.  An improvement - thank you!

**Comment by Grix** [comment]
Maybe in a next version I can add a secondary shortcut too. Any suggestion aside from the question mark? Like a letter or number
