### ISSUE TITLE
Feature request:  Allow timeline mode perspective view to be un-docked

### ISSUE THREAD

**Issue by dheista** [Grix/ildagen#8]
When editing, I'd love to use a second monitor and visualize the field of view in a separate window, allowing me to resize/expand the perspective window to be huge if I want to see it large

**Comment by Grix** [comment]
There's a button in the top right corner for increasing the size of the preview, to cover the whole window. 
Other than that, unfortunately undocking the timeline into a separate window won't happen. It's a limitation of the engine I am using that it doesn't natively support more than one window. So it will be very hard if not impossible to implement properly. So I'm closing the issue, sorry.

**Comment by dheista** [comment]
<img width="1975" alt="Screen Shot 2021-12-27 at 10 29 00 AM" src="https://user-images.githubusercontent.com/1724371/147485738-8080780a-85e1-4d3d-a114-fe0149335482.png">

Hmm - interesting, I don't see a button anywhere in the top right...  Is this a Mac issue?

**Comment by dheista** [comment]
Also - how do I get rid of the Playlist window in the visualization screen?  I think I enabled this (can't remember), but now can't figure out how to disable the display of this...

**Comment by Grix** [comment]
Hmm, it looks like the button for a large preview is not visible unless you have a DPI scaling of 1. That's a bug and I'll try to fix it.
As for the playlist, it was newly added in the previous version and so far there is no way to hide it, unfortunately... Is it enough to just not show it in the large preview view or do you also want to hide it in the normal view?

**Comment by dheista** [comment]
Well yeah - it doesn't really interfere, as long as I can maximize the preview window for some computers.  Would be great to see the button in larger scaling modes.
